# Generated by Django 5.2.7 on 2025-11-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0003_alter_comment_game_alter_comment_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='genre_images/', verbose_name='Фото'),
        ),
    ]
