# Generated by Django 5.2.7 on 2025-11-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0004_genre_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='mods/', verbose_name='Файл мода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='game_vault.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Мод',
                'verbose_name_plural': 'Моды',
            },
        ),
    ]
