# Generated by Django 5.2.7 on 2025-11-08 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0005_mod'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_system', models.CharField(max_length=150, verbose_name='Операционная система')),
                ('processor', models.CharField(max_length=150, verbose_name='Процессор')),
                ('op_memory', models.CharField(max_length=150, verbose_name='Оперативая память (ОЗУ)')),
                ('video_card', models.CharField(max_length=150, verbose_name='Видеокарта')),
                ('hard_memory', models.CharField(max_length=150, verbose_name='Память на диске')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_vault.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Системные требования',
                'verbose_name_plural': 'Системные требования',
            },
        ),
    ]
