# Generated by Django 5.2.7 on 2025-11-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0006_systemrequirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_content',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Короткое содержание'),
        ),
    ]
