# Generated by Django 5.2.7 on 2025-11-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0007_game_short_description_news_short_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='game_vault.genre', verbose_name='Жанр'),
        ),
    ]
