# Generated by Django 5.2.7 on 2025-11-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0008_remove_game_genre_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Короткое описание'),
        ),
    ]
