# Generated by Django 5.2.7 on 2025-11-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0009_alter_game_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_content',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое содержание'),
        ),
    ]
