# Generated by Django 5.2.7 on 2025-11-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0010_alter_news_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_content',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Короткое содержание'),
        ),
    ]
