# Generated by Django 5.2.7 on 2025-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0011_alter_news_short_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Издатель'),
        ),
        migrations.AddField(
            model_name='game',
            name='released',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата выхода'),
        ),
    ]
