# Generated by Django 5.2.7 on 2025-11-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0012_game_platform_game_publisher_game_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='year',
        ),
    ]
