# Generated by Django 5.2.7 on 2025-11-09 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0014_alter_game_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games_images/extra/', verbose_name='Доп. изображение')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='game_vault.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Изображение игры',
                'verbose_name_plural': 'Изображения игр',
            },
        ),
    ]
