# Generated by Django 5.2.7 on 2025-11-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_vault', '0015_gameimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trailer',
            field=models.TextField(blank=True, null=True, verbose_name='HTML-код трейлера'),
        ),
    ]
